### ISSUE TITLE
Glitching out Items from Deaths in Arena

### ISSUE THREAD

**Issue by Lomaticc** [alkarinv/BattleArena#1]
Arena Bug where players are able to glitch out items : http://puu.sh/11PzJ

**Comment by alkarinv** [comment]
I think I have fixed this in version 3.6.2. Hopefully.

But this bug only happens with multiverse when there is an 
Failed to handle packet: java.lang.IllegalStateException: Failed to add player. EntityPlayer..... already is in chunk 14, -6.

What happens is i put into the login/respawn event the location where they should respawn, and remove them from my list.
Later on some plugin crashes the login event causing them to never log in.
They log back in but are no longer in the list so are still in the arena area.

I have changed it so that BattleArena should act last on respawn/onjoin events, which should fix this problem

Otherwise the solution is to add clearInventory in the onDeath stage.  So that items are not dropped in the first place
