### ISSUE TITLE
matchEnableForceStart  not working since 1.4.7

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#105]
I have upgraded to 1.4.7 and now when players join spleef and such the forcestart time does not work when set to true. 

http://pastebin.com/Yux1Faqg   - ba config

http://pastebin.com/ntiEXsvP  - spleef config

**Comment by alkarinv** [comment]
Which version of BattleArena are you using?

If you are using the latest, 3.7.9.4+, I changed it so that forceStart respects the minimum number of players needed.  Looking at both of your configs though it looks like it should still work...
I'll try this locally, and sorry about the delay, holiday has been busy.

**Comment by stevewall85** [comment]
yes im using 3.7.9.4 it auto updates i will try to play with the configs some more and reload the jars and see what i can come up with

**Comment by alkarinv** [comment]
Let me know, or let me know when you are online and I'll come help you out.

**Comment by stevewall85** [comment]
ugh sry i havent got around to it yet im smoothing some configs for other plugs and got held up i wil see what i can do about this tonight

**Comment by alkarinv** [comment]
This should be fixed in the newest versions!
