### ISSUE TITLE
ould not pass event PluginDisableEvent to ProtocolLib v3.1.3-SNAPSHOT

### ISSUE THREAD

**Issue by TKDGRL** [alkarinv/BattleArena#246]
I'm running the most current versions of all your plugins as of 02.17.14, but receive the below error which then cases the server to hang and crash.

1:19:37 PM CONSOLE: ERROR]: Encountered an unexpected exception
1:19:39 PM CONSOLE: [INFO] Stopping server
1:19:39 PM ArenaCTF: Disabling ArenaCTF v1.2.9
1:19:41 PM CONSOLE: ERROR]: Could not pass event PluginDisableEvent to ProtocolLib v3.1.3-SNAPSHOT
1:19:42 PM CONSOLE: java.lang.OutOfMemoryError: PermGen space
1:19:42 PM CONSOLE: Method) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Method) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Method) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Method) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM CONSOLE: Source) ~[?:1.7.0]
1:19:42 PM ArenaCTF: v1.2.9 stopping!
1:19:46 PM CONSOLE: ERROR]: Error occurred (in the plugin loader) while cancelling tasks for ArenaCTF v1.2.9 (Is it up to date?)
1:19:48 PM ArenaSpleef: Disabling ArenaSpleef v1.4.9
1:19:52 PM CONSOLE: ERROR]: Could not pass event PluginDisableEvent to ProtocolLib v3.1.3-SNAPSHOT
1:19:52 PM CONSOLE: java.lang.OutOfMemoryError: PermGen space
1:19:52 PM ArenaSpleef: v1.4.9 stopping!
1:19:52 PM CONSOLE: ERROR]: Error occurred (in the plugin loader) while cancelling tasks for ArenaSpleef v1.4.9 (Is it up to date?)
1:19:52 PM ArenaPaintball: Disabling ArenaPaintball v1.2.0
1:19:54 PM CONSOLE: ERROR]: Could not pass event PluginDisableEvent to ProtocolLib v3.1.3-SNAPSHOT
1:19:55 PM CONSOLE: java.lang.OutOfMemoryError: PermGen space
1:19:55 PM ArenaPaintball: v1.2.0 stopping!
1:19:57 PM CONSOLE: ERROR]: Error occurred (in the plugin loader) while cancelling tasks for ArenaPaintball v1.2.0 (Is it up to date?)
1:19:57 PM BattleArena: Disabling BattleArena v3.9.5.8.5

**Comment by alkarinv** [comment]
Is this happening when you stop the server? or sometime before? This error probably isn't BattleArena or any of the extension plugins

This error happens to CraftBukkit when: 1) you do too many reloads, which causes the unnecessary classes to pile up and you run out of permgen space(which is different than your heap size); 2) You have lots of plugins that have lots of classes (most likely); 3) some plugin is doing something bad and creating way too many classes (Potentially ProtocolLib (which isn't a plugin of mine))

Regardless the fix is to give java more permgen space at the start.  You can do that by using this setting in your startup script.

-XX:MaxPermSize=512m

That should increase the size enough to not have this problem, between craftbukkit and a couple plugins usually you are very close to the max available permgen size.  If that doesn't work, then it's potentially ProtocolLib, but I doubt that.

**Comment by TKDGRL** [comment]
Thanks Alkarinv - you Sir are the best!

**Comment by alkarinv** [comment]
No worries. As this isn't really a bug I'm going to close down this issue. Hopefully what I gave you will fix the problem!

**Comment by TKDGRL** [comment]
Apparently my host is stingy and won't give me 512. They did give me 256 so
hopefully that will help. And yes feel free to close the issue.
Thanks again.
