### ISSUE TITLE
Scoreboard issue part 2

### ISSUE THREAD

**Issue by dutchy1001** [alkarinv/BattleArena#260]
Sorry to open this again.

I have removed the NametagEdit from my server restarted several times since but the client crash still happens. All names are back to default color in the TAB list(white).

Here my client crash report:
http://pastebin.com/umRmW2JR

Any more info needed let me know.

My server adress is "debocraft.redirectme.net"
Because of rebuilding the server it's not on 24/7 only when I work on it for now.

regards 
dutchy

**Comment by dutchy1001** [comment]
Ok this time my mistake I copy/paste instead of cut/paste.

Sorry about this.

**Comment by alkarinv** [comment]
No problem. I would be very careful with the NametagEdit plugin.  Because of it's packet manipulation it has the potential to crash clients.  It will conflict with any plugin that uses Bukkit scoreboards, mcMMO, Heroes, scoreboard stats, BattleArena, etc. Really NametagEdit should be doing more checks to ensure their packet sending doesn't do this and I would say it's a bug in their code.  Essentially if no one ever uses the scoreboard their code works fine... if any one else does, then you have crash potential.

This is why Bukkit frowns on plugins that bypass the BukkitAPI and manipulates internals directly.

**Comment by dutchy1001** [comment]
I just have to find another plugin that changes the tablist color. 
Any suggestions?

**Comment by alkarinv** [comment]
I asked on Bukkit, got this reply

http://dev.bukkit.org/bukkit-plugins/nametags/

It's made by  one of the developers of Bukkit, so I trust it.

**Comment by dutchy1001** [comment]
Thank you for your help and explanations. Nametags is great
