### ISSUE TITLE
BUG BATTEL PLUGIN

### ISSUE THREAD

**Issue by ghost** [alkarinv/BattleArena#269]
http://youtu.be/bDes8ynfVbA

**Comment by alkarinv** [comment]
Hey elespawol. That isn't actually a bug with BattleArena but with bukkit servers.  There are several tricks you can do such as break through blocks, use block placing where you shouldn't be able place to jump up higher.

Basically, not much I can do because it's a client/server interaction bug.  

I would suggest making the floor at least 2-3 layers thick, usually players can't glitch that without speed hacks.
