### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by Dakotacrans** [alkarinv/BattleArena#29]
When people leave the game because they have to go or they have a bad connection they sometimes get stuck with the stuff in the game and loose there stuff, you should make some sort of feature that kicks everyone out of all of the paint ball/pvp/ spleef arenas with one command or make it so it does that before reloading a server or restarting a server so people always get to keep there items.

**Comment by alkarinv** [comment]
They shouldn't be losing their items when they have a bad connection or just leave.  I do check for that, if they are losing them it's a bug.

You can do the command "arena cancel all" to cancel all the ongoing matches.  I actually do this when the server is restarting, but the server sometimes does strange things during that time, and it doesn't look like it always gives people back what I say.

**Comment by alkarinv** [comment]
This problem should be resolved now.  Also there are now 2 other ways to deal with inventory.

The newest version of BattleArena 3.6.9.3+ has an Inventory restoration for times when it's just not possible to restore normally (like on server crash, sometimes during a reload/restart, various other strange times).

If you don't want to deal with any inventory issues you can also use the option "noInventory" on preReqs to make it so that they can't join with inventory.

**Comment by Dakotacrans** [comment]
That's awesome!
