### ISSUE TITLE
Start match without a full group of players

### ISSUE THREAD

**Issue by alkarinv** [alkarinv/BattleArena#34]

**Comment by perfk** [comment]
This could work like one player types /arena vote [arena name] this will give all the players that is queued for that arena a /vote yes /vote no option. and maybe a "there is x ppl waiting to join said arena"

**Comment by alkarinv** [comment]
Yeah, that would work well with your other enhancement.

For this one though I just want people to be able to join a 20 v 20, and then have some option to be able to start if only 8 people are in the queue

**Comment by darrenstraight** [comment]
Brilliant plugin thank you for all your work on it and yes Id certainly like to see this feature so if everyone in the queue  are still missing a few people the match can start anyway, simple solution would be nice.

Maybe a min/max players required parameter before game starts, so you could say define 20 players max but if it reaches a minimum of 16 players for example (define in config) a countdown starts? Of course what happens if there's 14-15 players etc but they still want to start.

**Comment by alkarinv** [comment]
I want this badly... going to be trying to make this happen today.

How i'm trying to make it work is this.  If you specify something like nTeams: 2-10, teamSize: 1, and the match has a waiting room.  Then it will open up the match when two players join, and during the waitroom phase, others can be added as they join up to 10 or until the time runs out.

**Comment by darrenstraight** [comment]
Great news, looking forward to seeing if you can implement this. Good luck.

**Comment by alkarinv** [comment]
Alright, So I've done this is the newest version of BattleArena that I'll be releasing tonight.  It works like this, there is a minimum number of people that need to be there in order to start.. but then you can have up to whatever.

nTeams: 2

teamSize: 3-5

if you have a waitroom set on this, then a match will start when 6 players join, but other players can still join up to 15 seconds before the match starts.

It's not ideal, but it's a start :)
