### ISSUE TITLE
[feature request] area regen cubiod for all battle arena types

### ISSUE THREAD

**Issue by zippa713** [alkarinv/BattleArena#53]
It'd be a great feature to add arena regeneration after battles  simular to your spleef layer but cubiod not layer or even better be able to set multiple cubiods like multiple layers of spleef!

If we want people to be able to build during battle but erase after battle for a clean match on next round.

I want to make a paintball arena thats empty and flat; where you get say 16 snow blocks, 60 snowballs, 4 wood planks (to craft a table), and a spade... When the match starts you can either build with the snow to have a fort or break them into more ammo! bigger teams bigger forts more ammo

**Comment by alkarinv** [comment]
I use Worldedit/Worldguard for the layers, so I think that it should work for any selection that is pasteable normally( unsure of this though), but I don't specify anywhere that it needs to be cuboid.

You can already add multiple layers to spleef!! just do /spleef setlayer 2, or /spleef setlayer 3.

Herm, that one is a bit trickier because the arena has to regen afterwards to it's previous state... that means either worldguard or logblock.  If it's worldedit I would need to save the arena as a schematic, and repaste it.  <- this has been known to lag servers if the area is big enough.  If you still want that I can add it to the list of enhancements!

**Comment by zippa713** [comment]
would logblock work better or at all with your plugin to reset after each map automatically? If nothing else the world edit will do for now.

**Comment by alkarinv** [comment]
Arenas now have reset capabilities! 
Version 3.7.0.5+
