### ISSUE TITLE
1.4.6 errors

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#85]
i have updated to 1.4.6 and i get this error on start up

http://pastebin.com/zQghrtXd

the plugin still runs an works as far as i can tell

**Comment by alkarinv** [comment]
That is saying that you are trying to give a class that doesn't exist.  Usually it looks something like this

<pre>
giveClass:
    default: gladiator
</pre>

so check that out.  I'll try and fix it so that if a class or that section doesn't exist that it doesnt throw errors like that.

**Comment by stevewall85** [comment]
i looked it over and it seems alright but heres the cfg

http://pastebin.com/Mbzrptf7

**Comment by alkarinv** [comment]
Yeah its my problem.. im nearly 100% sure that its inside the arena.onSpawn.giveClass: where the default is [].  So it does freak out on that, it doesnt know what type of class "[]" is.  But it won't break anything but giving them classes, which is why it works fine.

Take out the giveClass in arena.onSpawn, and you won't get annoying errors any more :)
