### ISSUE TITLE
Error loop when leaving a DM

### ISSUE THREAD

**Issue by solivero** [alkarinv/BattleArena#89]
22:43:56 [SEVERE]       at mc.alk.arena.competition.match.Match.leaveArena(Match
.java:691)
22:43:56 [SEVERE]       at mc.alk.arena.competition.match.PerformTransition.tran
sition(PerformTransition.java:214)
22:43:56 [SEVERE]       at mc.alk.arena.competition.match.Match.leaveArena(Match
.java:691)
22:43:56 [SEVERE]       at mc.alk.arena.competition.match.PerformTransition.tran
sition(PerformTransition.java:214)
22:43:56 [SEVERE]       at mc.alk.arena.competition.match.Match.leaveArena(Match
.java:691)
22:43:56 [SEVERE]       at mc.alk.arena.competition.match.PerformTransition.tran
sition(PerformTransition.java:214)

These are the errors, created when leaving a DM, looping until the player is kicked for flying. It creates a huge lagspike and wipes the inventory of the player.

**Comment by alkarinv** [comment]
Ouch!!!, I'll see if i can get out a fix right now.

**Comment by alkarinv** [comment]
On second thought, let me see you BattleArena/config.yml, can you pastebin it somewhere?

Still might be a bug though

**Comment by solivero** [comment]
http://pastebin.com/eYmQtYg2

**Comment by alkarinv** [comment]
Ok, so this is probably my auto updaters fault.

You have two deathMatch.onLeave sections

You just want the first one that says

<pre>
    onLeave:
        options: [restoreAll]
</pre>

The other one you should delete.  That one is saying that when you leave (aka teleport out) you should teleport out... which calls onLeave... and bam.  I really need to fix this so that you can't specify teleportOut in onLeave

**Comment by solivero** [comment]
Ah i see! Thanks man :)
