### ISSUE TITLE
battlearena crashing server

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#95]
When some one joins the arena and starts a match the console gets spammed with the error below
I use world guard and towny all upto date since yesterday. All for 1.4.6 
Also the plugin does work while the errors are going on I can change classes and attack since its a pvp arena. 

http://pastebin.com/LFcEDSyY  -error
http://pastebin.com/NPazfYQ5- config

**Comment by alkarinv** [comment]
For some reason the world guard region you set up with the arena got deleted.  So when a player moves it checks to see whether they should be able to leave, and since there is no region it freaks out.

I fixed this in the code so it won't spam that error.  But you should also redefine the region.

http://dev.bukkit.org/media/files/663/197/BattleArena.jar
